name: vaxpass-frontend-deploy

defaults:
  run:
    working-directory: fe

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Deployment Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Install Dependencies
        run: npm install
      - name: Build Front End Distribution
        run: npm run build
      - name: Deploy Front End Build to S3 Bucket
        run: aws s3 sync ./build/ s3://vaxpass-platform --delete
      - name: Invalidate CloudFront CDN Cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CDN_DISTRIBUTION_ID }} --paths "/*"
